# Site Settings
title: Alex Fu - Google Resume
url: 'http://fuxiaoalex.github.io'
baseurl: '/resume' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alex Fu
# tagline: Solution Consultant, gPS Ads
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Seasoned tech professional with work exprience in Software Engineering, Product/Program management & Tech
Service. Multi-national study & work experience across Unitied States, Italy & China. Experience in both enterprise
& consumer tech giants. Know 'everything' and nothing. Just joined Google in January 2017."

#sidebar links
email: xiaofu@google.com
phone: (86)15705276262
# website: moma.corp.google.com/person/xiaofu
linkedin: xiaofu
github: fuxiaoalex
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics:

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

theme: jekyll-theme-minimal
